#!/bin/bash
while getopts "s:d:l:" arg
	do
		case $arg in
			s)
			curl -H "API-Key: $OPTARG" https://api.vultr.com/v1/server/create --data 'DCID=40' --data 'VPSPLANID=201' --data 'OSID=167' --data 'SCRIPTID=337754' --data 'enable_ipv6=yes' --data 'enable_private_network=yes'
			;;
			d)
			subid=`curl -H "API-Key: $OPTARG" https://api.vultr.com/v1/server/list|awk '{print $1}'|cut -d '"' -f2`
			curl -H "API-Key: $OPTARG" https://api.vultr.com/v1/server/destroy --data "SUBID=$subid"
			;;
			l)
			curl -H "API-Key: $OPTARG" https://api.vultr.com/v1/server/list
			;;
		esac
	done
