#!/bin/bash
chown -R apache:apache /var/www/html/nextcloud/data/admin/files
cd `find /var/www/html -name occ -printf '%h\n'|sort|head -n 1`
sudo -u apache php occ files:clean
sudo -u apache php occ files:scan --all
