#!/bin/bash
rpm -qa | grep -qw aria2 || yum -y install aria2
cp -u aria2.conf /etc/aria2.conf
cp -u aria2.service /usr/lib/systemd/system
cp -u dht.dat /root/.aria2/dht.dat
cp -u dht6.dat /root/.aria2/dht6.dat
systemctl enable aria2
systemctl start aria2
