#!/bin/bash
./aria/install
firewall-cmd --zone=public --add-port=6800/tcp --permanent
firewall-cmd --reload
#aria2 webui
cd ~
wget https://github.com/mayswind/AriaNg/releases/download/1.3.7/AriaNg-1.3.7.zip
unzip -d AriaNG AriaNg-1.3.7.zip
rm -f AriaNg-1.3.7.zip
mv AriaNG /var/www/html/
chown -R apache:apache /var/www/html/AriaNG
