#!/bin/bash
pip install supervisor
rpm -qa | grep -qw aria2 || yum -y install aria2
echo_supervisord_conf > /etc/supervisord.conf
echo '[include]'>>/etc/supervisord.conf
echo 'files = /etc/supervisor/*.conf'>>/etc/supervisord.conf
mkdir /etc/supervisor
cp shadowsocks.conf /etc/supervisor/shadowsocks.conf
cp update_ip.conf /etc/supervisor/update_ip.conf
cp aria2.conf /etc/aria2.conf
cp aria2-supervisor.conf /etc/supervisor/aria2-supervisor.conf
cp supervisord.service /etc/systemd/system/supervisord.service
firewall-cmd --zone=public --add-port=6800/tcp --permanent
firewall-cmd --reload
systemctl enable supervisord.service   #自启动
systemctl start supervisord.service    #启动服务
