#!/bin/bash
init_config(){
	if [ ! -f /etc/shadowsocks.json ];then
		echo '''
		{
			"server":"host",
			"server_port":8379,
			"local_port":1080,
			"password":"password",
			"timeout":600,
			"method":"aes-256-cfb"
		}
		'''> /etc/shadowsocks.json
		rpm -qa | grep -qw firewalld || yum install firewalld
		systemctl start firewalld
		firewall-cmd --zone=public --add-port=8379/tcp --permanent
		firewall-cmd --zone=public --change-interface=eth0
		firewall-cmd --reload
	fi
}

get_ip(){
	#install ifconfig
	rpm -qa | grep -qw net-tools || yum -y install net-tools
	echo `ifconfig eth0| grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'` 
}

update_host(){
	host=`get_ip`
	# update shadowsocks
	sed -i "s/\"server\".*/\"server\":\"$host\",/" /etc/shadowsocks.json

	# update nextcloud
	configpath=`find /var/www/html -name config.php -print|sort -r|head -n 1`
	sed -i "s/0 => .*,/0 => \'$host\',/" $configpath
	sed -i "s/1 => .*,/1 => \'coyace.top\',/" $configpath
	# sync nextcloud files
	../cloud/scan
	# show result
	cat /etc/shadowsocks.json
}

#get local ip address
init_config
while getopts "ishabp:" arg
	do
		case $arg in
			a)
				get_ip
			;;
			p)
				password=$OPTARG
				sed -i "s/\"password\".*/\"password\":\"$password\",/" /etc/shadowsocks.json
				update_host
			;;
			i)
				rpm -qa | grep -qw python-setuptools || yum -y install python-setuptools
				sudo easy_install pip
				sudo pip install shadowsocks
				mv shadowsocks.service /usr/lib/systemd/system
				systemctl enable shadowsocks
				systemctl start shadowsocks
				echo "done"
			;;
			s)
				# handle dynamic ip
				# 滚动更新ip时需要更新ip地址
				update_host
				nohup ssserver -c /etc/shadowsocks.json -d start &
			;;
			b)
				rpm -qa | grep -qw wget || yum -y install wget
				wget –no-check-certificate https://github.com/teddysun/across/raw/master/bbr.sh
				chmod +x bbr.sh
				./bbr.sh
			;;
			h)
				echo "usage: -a see ip address,-i install shadowsocks,-s start server,-b install bbr"
			;;
		esac
	done
